name: hiding_adversarial_attacks
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - eagerpy
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - seaborn
  # ML, STATS & DEEP LEARNING
  - pytorch
  - pytorch-lightning
  - torchvision
  - cudatoolkit==11.1
  # OTHER TOOLS
  - optuna
  - mlflow
  # CODE FORMATTERS & TYPE CHECKING
  - black
  - mypy
  - pip:
     - -e .  # install git checkout of hiding_adversarial_attacks in editable mode
     - lightning-bolts
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
#  - jupyterlab
#  - pytest
#  - pytest-cov
#  - tox
#  - pre_commit
#  - nbdime
#  - nbstripout
#  - sphinx
#  - recommonmark
