name: hiding_adversarial_attacks
channels:
  - defaults
  - conda-forge
  - plotly
  - pytorch
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - eagerpy
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - seaborn
  - plotly
  # ML, STATS & DEEP LEARNING
  - pytorch
  - pytorch-lightning
  - torchvision
  - cudatoolkit==11.1
  - torchmetrics
  # XAI
  - captum
  # CONFIG MANAGEMENT
  - hydra-core
  # EXPERIMENT TRACKING & HYPERPARAMETER OPTIMIZATION
  - optuna
  - mlflow
  - neptune-client
  # CODE FORMATTERS & TYPE CHECKING
  - black
  - mypy
  # DEV PACKAGES
  - pre-commit
  - pip:
     - -e .  # install git checkout of hiding_adversarial_attacks in editable mode
     - lightning-bolts
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
